# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: GoDaddyDNS-v0.$(date:yy)$(DayOfYear).$(rev:r)-$(Build.SourceBranchName)
trigger:
- master
- issue*

pool:
  name: MacNetCorePools
  demands: npm

#Your build pipeline references an undefined variable named ‘buildExtractor.fullVersion’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: VersionExtractor@4
  name: buildExtractor
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(build.buildNumber)'

- task: TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: Npm@1
  displayName: 'ARecordManager node_modules install'
  inputs:
    workingDir: aRecordManager
    verbose: false

- task: Npm@1
  displayName: 'CNAMERecordManager node_modules install'
  inputs:
    workingDir: cnameRecordManager
    verbose: false

- task: PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    extensionVersion: '$(buildExtractor.fullVersion)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy *.vsix'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

